# Generated by Django 3.0.5 on 2025-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20250415_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='d_price',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
