# Generated by Django 3.0.5 on 2025-04-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20250422_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product_Type'),
        ),
    ]
