# Generated by Django 3.0.5 on 2025-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/multi/'),
        ),
    ]
