# Generated by Django 3.0.5 on 2025-04-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20250424_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecom.Product'),
        ),
    ]
